version: '3'
services:
  electrum:
    container_name: electrum-daemon
    image: internetportal/docker-electrum-daemon
    ports:
      - 7000:7000
    environment:
      ELECTRUM_USER: electrum
      ELECTRUM_PASSWORD: secret-password
      TESTNET: "False"
    volumes:
      - ./data:/data
    restart: unless-stopped
    network_mode: bridge
